source("getData.R")
source("Graphics.R")

blockData <<- getBlockData()
blockTimeData <<- getBlockTime()
poolData <<- getPoolData()
hashData <<- getNetworkHash()
stakeData <<- getStakeData()
feeData <<- getTicketFees()
windowTimeData <<- getWindowTime()
BTCUSD <<- getBTCUSD()
DCRBTC <<- getDCRBTC()
DCROHLC <<- getOHLC()
coinSupply <<- getCoinSupply()
reward <<- getReward()
poolValue <<- getPoolValue()
voteInfo <<- getVoteInfo()
